apiVersion: v1
kind: Service
metadata:
  name: sample-ms-demo
spec:
  selector:
    run: sample-ms-demo
  ports:
    - name: port1
      protocol: TCP
      port: 3333
      targetPort: 3333
    - name: port2
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort