apiVersion: v1
kind: Service
metadata:
  name: external-postgres-service
spec:
  selector:{}
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0

