apiVersion: v1
kind: Service
metadata:
  name: sample-ms-demo1
spec:
  selector:
    run: sample-ms-demo1
  ports:
    - name: port1
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: port2
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort